local settingsMenu = {
    {"&QT-settings"          , env .. "systemsettings5"                , nil},
	{"G&TK-settings"         , nil                                     , nil},
	{nil                     , nil                                     , nil},
	{"Key&board-settings"    , env .. "ibus-setup"                     , nil},
	{"Gamepad-&mapper"       , env .. "qjoypad"                        , nil},
	{nil                     , nil                                     , nil},
	{"&Printer-settings"     , env .. "system-config-printer"          , nil},
	{"&Keyring-configuration", env .. "seahorse"                       , nil},
	{"&Audio-settings"       , env .. "pavucontrol"                    , nil},
	{nil                     , nil                                     , nil},
	{"&GPU-settings"         , env .. "nvidia-settings"                , nil},
	{"&3D-accel' settings"   , env .. "driconf"                        , nil},
	{nil                     , nil                                     , nil},
	{"&Java-settings"        , env .. "jcontrol"                       , nil},
	{"Ja&va-policy"          , env .. "policytool"                     , nil},
	{"&Flash-settings"       , nil                                     , nil},
	{nil                     , nil                                     , nil},
	{"Awesome-t&heme"        , env .. edit .. " " .. beautiful.conffile, nil},
	{"A&wesome-configuration", env .. edit .. " " .. awesome.conffile  , nil},
}
return {
	{"&Settings"                , settingsMenu                        , beautiful.icons .. "Categories/preferences.png"      },
	{nil                        , nil                                 , nil                                                  },
	{"&Wine-manager"            , env .. "playonlinux"                , beautiful.icons .. "Applications/wine.png"           },
	{"System-&monitor"          , env .. "ksysguard"                  , beautiful.icons .. "Applications/system-monitor.png" },
	{"&Info-center"             , env .. "hardinfo"                   , beautiful.icons .. "Applications/system-info.png"    },
	{"&Help"                    , env .. terminal .. " -e man awesome", beautiful.icons .. "Applications/help-browser.png"   },
	{"&Cleaner"                 , env .. "bleachbit"                  , nil                                                  },
	{nil                        , nil                                 , nil                                                  },
	{"&User-manager (root)"     , env .. "gksudo kuser %i -caption %c", nil                                                  },
	{"&Partition-manager (root)", env .. "gksudo gparted"             , beautiful.icons .. "Applications/partitioner.png"    },
	{"SMART-&inspector (root)"  , env .. "gksudo gsmartcontrol"       , beautiful.icons .. "Applications/disk-configurer.png"},
	{"C&leaner (root)"          , env .. "gksudo bleachbit"           , nil                                                  },
}
