local settings_menu = {
    {"&QT-settings",           env .. "systemsettings5",                 nil},
	{"G&TK-settings",          nil,                                      nil},
	{nil,                      nil,                                      nil},
	{"Key&board-settings",     env .. "ibus-setup",                      nil},
	{"Gamepad-&mapper",        env .. "qjoypad",                         nil},
	{nil,                      nil,                                      nil},
	{"&Printer-settings",      env .. "system-config-printer",           nil},
	{"&Keyring-configuration", env .. "seahorse",                        nil},
	{"&Audio-settings",        env .. "pavucontrol",                     nil},
	{nil,                      nil,                                      nil},
	{"&GPU-settings",          env .. "nvidia-settings",                 nil},
	{"&3D-accel' settings",    env .. "driconf",                         nil},
	{nil,                      nil,                                      nil},
	{"&Java-settings",         env .. "jcontrol",                        nil},
	{"Ja&va-policy",           env .. "policytool",                      nil},
	{"&Flash-settings",        nil,                                      nil},
	{nil,                      nil,                                      nil},
	{"Awesome-t&heme",         env .. edit .. " " .. beautiful.conffile, nil},
	{"A&wesome-configuration", env .. edit .. " " .. awesome.conffile,   nil},
}
return {
	{"&Settings",                 settings_menu,                        beautiful.get_icon("preferences-desktop")},
	{nil,                         nil,                                  nil},
	{"&Wine-manager",             env .. "playonlinux",                 beautiful.get_icon("wine")},
	{"System-&monitor",           env .. "ksysguard",                   beautiful.get_icon("system-monitor")},
	{"&Info-center",              env .. "hardinfo",                    beautiful.get_icon("system-info")},
	{"&Help",                     env .. terminal .. " -e man awesome", beautiful.get_icon("help-browser")},
	{"&Cleaner",                  env .. "bleachbit",                   nil},
	{nil,                         nil,                                  nil},
	{"&User-manager (root)",      env .. "gksudo kuser %i -caption %c", nil},
	{"&Partition-manager (root)", env .. "gksudo gparted",              beautiful.get_icon("partitioner")},
	{"SMART-&inspector (root)",   env .. "gksudo gsmartcontrol",        beautiful.get_icon("disk-configurer")},
	{"C&leaner (root)",           env .. "gksudo bleachbit",            nil},
}
